### ISSUE TITLE
Location of libMVCI32.so

### ISSUE THREAD

**Issue by aselafernando** [diorcety/j2534-tools#1]
Hi,

Do you have a URL for the libMVCI32.so library? Without this I can't get the MVCI cable to work on linux. I'm trying to avoid having to  decipher the J2534 functions into a serial bitstream.

Thanks,
Asela

**Comment by diorcety** [comment]
hi, what do you trying to achieve? These sources was created in order to simulate an OBD device containing two CAN bus (low et high speed), using two cheap MVCI clone Chinese devices. Not sure that the driver is available on Linux.

**Comment by aselafernando** [comment]
I am trying to write a headunit application on the raspberry pi that could communicate with the car via the Mini VCI cable. I was hoping that you had access to a linux library for the Mini-VCI that could translate the J2534 commands into the serial bitstream. That way I could avoid having to use wine to run the DLL. But it looks like there doesn't seem to be a library available for Linux. The cable appears as a serial port (using FTDI standard drivers in Linux). I also tried sniffing the serial bitstream by implementing a proxy of ftd2xx.dll on windows and comparing with the J2534 commands sent, however the protocol used isn't straight forward to reverse engineer.
